- .gitignore
- .rustfmt.toml
- Cargo.toml
- LICENSE
- src/comments.rs
- src/lexing.rs
- src/lib.rs
- src/media_type.rs
- src/parsed_source.rs
- src/parsing.rs
- src/text_info.rs
- src/types.rs
This is a very rough initial implementation. There is not much documentation and barely any tests (just the bare minimum to get going).
After we've agreed on the implementation I'll spend some time adding tests and do the CI.
Downstream PRs:
* https://github.com/denoland/deno_lint/pull/834
* https://github.com/denoland/deno_graph/pull/23
* https://github.com/denoland/deno_doc/pull/151
* https://github.com/denoland/deno/pull/11780
I will integrate this later into dprint-plugin-typescript.
> feat: initial implementation of deno_ast

- src/comments.rs
- src/lexing.rs
- src/lib.rs
- src/parsed_source.rs
- src/parsing.rs
- src/text_encoding.rs
- src/text_info.rs
- src/types.rs
> chore(tests): add more tests

- src/media_type.rs
This reverts commit a0e8a45467fcf377541dad3c313b2527edf5a154.
> Revert "feat: Make MediaType::from_path public (#18)"

- scripts/05_branch.ts
- scripts/README.md
- scripts/helpers/crate.ts
Small fixes from doing a release.
> chore: fix scripts to not include an extra brace

- .github/workflows/ci.yml
- Cargo.toml
- src/lexing.rs
- src/parsing.rs
> feat: upgrade to swc_ecmascript 0.95.0

- Cargo.toml
- src/transpiling/mod.rs
> feat: upgrade swc_ecmascript to 0.111

- src/lib.rs
- src/text_changes.rs
Extracted this out of dnt and improved it. It will be used for `deno vendor`.
> feat: Text Changes API

- Cargo.toml
- src/parsing.rs
This upgrade should fix https://github.com/denoland/deno_lint/issues/1011
See also https://github.com/dprint/dprint-swc-ecma-ast-view/pull/34
> feat: upgrade swc and dprint-swc-ecma-ast-view

- scripts/01_setup.ts
- scripts/02_build.ts
- scripts/03_test.ts
- scripts/04_confirm.ts
- scripts/05_branch.ts
- scripts/helpers/mod.ts
- scripts/helpers/repo.ts
- scripts/reset.ts
Separated out the concept of "crates" and "repos" as there can be multiple crates in a repo.
> chore: update build/test/release scripts to include eszip

- src/transpiling/mod.rs
See https://github.com/swc-project/swc/issues/3739
> fix: surface diagnostic for octal literals and decimals with leading zeros

- src/transpiling/mod.rs
Temporarily reverting this one because it causes source maps to have blank source file names and there's too much to deal with WRT the latest swc upgrade (so let's do a follow up PR).
Reverts denoland/deno_ast#87
> Revert "fix: allow specifying a base for source maps"

- src/transpiling/mod.rs
Adding a test here for https://github.com/denoland/deno/pull/14930 because it will run faster. Also, less tests to run in the CLI.
> chore: add test for transpiling bitshift in for loop in typescript

- src/media_type.rs
For the future. I want to use this function from deno_graph in the CLI.
Todo:
> feat: MediaType::from_specifier_and_headers

- scripts/01_setup.ts
- scripts/02_build.ts
- scripts/03_test.ts
- scripts/05_branch.ts
- scripts/deps.ts
- scripts/repos.ts
- scripts/reset.ts
Had this in my working tree from a few weeks back.
> chore: update denoland/automation

- src/media_type.rs
> fix: correct media type for deno://lib.deno.d.ts

- Cargo.lock
- Cargo.toml
- scripts/deps.ts
- src/transpiling/transforms.rs
Need to test this out and open downstream prs.
> feat: upgrade dependencies (swc_ecma_parser 0.122.19)

- src/cjs_parse.rs
Ref https://github.com/denoland/deno/issues/16565
> fix(cjs): analyze exports in chained assignment

- src/transpiling/mod.rs
For https://github.com/denoland/deno/issues/17112
> fix: raise diagnostic when transpiling nullish coalescing with logical operator

- src/parsing.rs
- src/transpiling/mod.rs
- src/types.rs
Need to test this change downstream.
> feat: show source code text in diagnostic

- Cargo.lock
- Cargo.toml
- src/transpiling/mod.rs
Updating deno_ast because I'm going to do a deno_graph update soon
> feat: swc_ecma_parser 0.124

- deno.json
- scripts/04_confirm.ts
- scripts/README.md
Improvements from the last deno_ast release.
> chore: improve release script

- Cargo.lock
- Cargo.toml
- src/transpiling/mod.rs
- src/transpiling/transforms.rs
Some improvements I did to swc.
> feat: use two spaced indents instead of four when transpiling

- Cargo.lock
- Cargo.toml
Closes https://github.com/denoland/deno/issues/19595
> fix: pin more swc dependencies

- Cargo.lock
- Cargo.toml
- scripts/repos.ts
> feat: swc_ecma_parser 0.137.15

- src/transpiling/mod.rs
> fix: include explicit resource management helpers

- src/transpiling/mod.rs
- src/transpiling/transforms.rs
Oops. I didn't read the output carefully enough.
> fix: actually fix var_decl_imports with jsx automatic

- src/transpiling/jsx_precompile.rs
This is a bit of an oddity with SWC's AST format. It treats negative numeric literals as an UnaryExpression 🤷
> fix: negative numeric JSX attributes not inlined

- src/transpiling/jsx_precompile.rs
In the new JSX transform we have an optimization that bypasses `jsxAttr` with boolean attributes.
```jsx
// input
<input type="checkbox" checked />
// output
const tpl = [`<input type="checkbox" checked>`]
jsxTemplate(tpl);
```
But we can only apply this optimization for known HTML boolean attributes. If it's not part of the boolean attributes in the HTML spec, then we should always fall back to `jsxAttr`, because it might be something framework specific.
Ran into this while trying to switch the Fresh size over to the `precompile` transform.
> fix: only optimize known boolean jsx attrs

- Cargo.lock
- Cargo.toml
> fix: update swc_ecma_parser 0.141.22

- Cargo.lock
- Cargo.toml
- src/lib.rs
Also has fix from https://github.com/swc-project/swc/pull/8296
> fix: add back accidentally removed export for swc::dep_graph

- Cargo.lock
- Cargo.toml
For https://github.com/denoland/deno/issues/21258
> fix: upgrade swc_ecma_parser 0.141.26

- Cargo.lock
- Cargo.toml
- README.md
- src/cjs_parse.rs
- src/comments.rs
- src/dep.rs
- src/diagnostics.rs
- src/lib.rs
- src/parsed_source.rs
- src/parsing.rs
- src/scopes.rs
- src/transpiling/mod.rs
- src/types.rs
This is mostly a straight move down from the CLI. We can work on improving this more in the future, but for now let's just get this in.
Part of https://github.com/denoland/deno/issues/22117
Co-authored-by: lucacasonato <lucacasonato@users.noreply.github.com>
> feat: move `Diagnostic` trait from CLI down here

- src/transpiling/mod.rs
> feat(BREAKING): EmitOptions - combine inline_source_map and inline_sources

- README.md
- scripts/01_setup.ts
- scripts/02_build.ts
- scripts/03_test.ts
- scripts/04_confirm.ts
- scripts/reset.ts
- scripts/update_swc_deps.ts
> chore: add swc upgrade instructions

- Cargo.lock
- Cargo.toml
- src/transpiling/mod.rs
- src/transpiling/transforms.rs
~~Need to fix tests in downstream crates.~~
Closes https://github.com/denoland/deno_ast/pull/220
> fix: upgrade swc (swc_ecma_parser 0.143.11)

- Cargo.lock
- Cargo.toml
Let's try bumping swc again to see if that will fix the ci in the cli.
> fix: update to swc_ecma_parser 0.143.12

- Cargo.lock
- Cargo.toml
Includes https://github.com/swc-project/swc/pull/8819
> fix: update swc_visit 0.5.12

- Cargo.lock
- Cargo.toml
- src/transpiling/mod.rs
- src/transpiling/transforms.rs
Reverting due to https://github.com/swc-project/swc/issues/8840
> fix: revert swc_ecma_parser to 0.143.5

- rust-toolchain.toml
- src/emit.rs
- src/lib.rs
- src/source_map.rs
- src/transpiling/jsx_precompile.rs
- src/transpiling/mod.rs
Slightly simplifies the usage of `SourceMap` in our code.
> feat: add `SourceMap` wrapper

- src/transpiling/jsx_precompile.rs
This PR fixes an issue which would lead to content being escaped twice when `Fragments` with single children were used.
```tsx
function Foo(props) {
return <>{props.children}</>
}
const nodes = <>{'"test"'}</>
const final = <Foo>{nodes}</Foo>
// Would be transpiled to something like this
function Foo(props) {
return jsxEscape(props.children)
}
const nodes = jsxEscape('"test"')
const final = jsx(Foo, { children: nodes })
```
The issue occurred because of an incorrect assumption that we could optimize single string or expression child Fragments away to a string. But when the string is passed around we don't know whether the string has already been escaped or not, so the string will be escaped again.
The solution is to drop that faulty optimization and always materialize a container element. …
> fix: precompile double escape with Fragments

- Cargo.lock
- Cargo.toml
Includes fix at https://github.com/swc-project/swc/commit/91e92ececab33c2258eeb659803da9a549e7591a
> fix: update swc for emit named type in mapped types fix

- Cargo.lock
- Cargo.toml
- src/diagnostics.rs
Updates for https://github.com/unicode-rs/unicode-width/pull/45
Just spent an hour confused.
> fix: require unicode-width >= 0.1.13

- Cargo.lock
- Cargo.toml
Has https://github.com/swc-project/swc/pull/9342
> fix: swc_ecma_codegen 0.154.4

- Cargo.toml
> fix: swc_ecam_ast 0.118.1

- Cargo.lock
- Cargo.toml
I'll do a deno_ast upgrade after this PR.
> fix: swc_ecma_transforms_typescript 0.198

- src/parsed_source.rs
- src/parsing.rs
Aligns with https://github.com/denoland/deno_graph/pull/421
> fix: get_leading_comments() should take hashbang into account

- Cargo.lock
- Cargo.toml
- src/transpiling/mod.rs
* https://github.com/swc-project/swc/issues/10372
* https://github.com/swc-project/swc/issues/10331
* https://github.com/swc-project/swc/issues/10329
> fix: upgrade swc and add back explicit resource management

- src/transpiling/jsx_precompile.rs
- src/transpiling/mod.rs
Will fix .. https://github.com/denoland/deno/issues/30080.
> fix: default "jsxImportSource" to "react"

- Cargo.lock
- Cargo.toml
Downstreaming:
- https://github.com/swc-project/swc/pull/11130
- https://github.com/denoland/deno/issues/30858
- https://github.com/swc-project/swc/pull/11139
- https://github.com/denoland/deno/issues/30216
> fix: swc_ecma_parser 24
