Cargo.toml
README.md
src/comments.rs
src/lexing.rs
src/parsed_source.rs
src/parsing.rs
src/text_info.rs
src/types.rs

Adds the initial documentation to deno_ast. Will follow up with another commit that adds more tests and implements the CI.
Part of #2.

docs: add initial documentation

---

src/text_info.rs

This change is for consistency with the other methods.

refactor: `get_span_text` to `span_text`

---

src/media_type.rs

feat: Make MediaType::from_path public

---

Cargo.toml
README.md
src/comments.rs
src/parsed_source.rs
src/parsing.rs

Closes #8.
This will simplify deno_lint a little bit and allow us to re-use the cached source files for linting in the LSP again.

feat: ability to parse with scope analysis applied

---

src/parsing.rs
src/types.rs

This is the only thing I need now to integrate deno_ast into dprint-plugin-typescript. The `span` is used for some better error messages (perhaps in the future we could merge something into deno_ast to show the code where a diagnostic occurred).

feat: add span to diagnostic

---

src/media_type.rs

Closes #41.
Since this depends on the version of TypeScript I think it's better to just have this in the CLI.

refactor: remove `as_ts_script_kind` from `MediaType`

---

src/media_type.rs

Let me know if you have a suggestion for a better name.

feat: add method to `MediaType` for telling if declaration file media type

---

src/media_type.rs

Some mime type registries associate this content type with the .jsx
extension.
Examples:
- https://github.com/samuelneff/MimeTypeMap/blob/master/MimeTypeMap.cs#L273
- https://github.com/abonander/mime_guess/blob/492bece6d9b3253aeeb42d78d9358352d66ee935/src/mime_types.rs#L568

fix: add text/jscript to content type matchers

---

.github/workflows/ci.yml

From now on, when we merge a commit to main that includes a version in the commit message and has the Cargo.toml version bumped, it will automatically do a cargo publish on deno_ast, tag it, then do a GH release with changelog.

chore: cargo publish, tag, and do a GH release on cargo version change merge to main

---

.github/workflows/ci.yml

Forgot this in the last commit. CI on main will fail.

chore(ci): use deno

---

src/text_changes.rs

Tried integrating the text changes api into dnt and ran into this issue.

fix: text_changes with same start

---

src/parsed_source.rs
src/transpiling/mod.rs

This fixes the situation where the source map source name is the full name of the file, potentially leaking information in the source map which is undesirable.  This allows specifying a base (as well as specifies the base when doing a transpile) which will make the source file listed as relative of the source.

fix: allow specifying a base for source maps

---

src/text_changes.rs

I think I accidentally added this. It makes no sense.

refactor: remove TextChange.as_source_range

---

src/text_changes.rs

If this occurs, it's helpful to include the text change information.

fix: include text changes in panic message

---

src/transpiling/mod.rs

This will allow us to implement more targeted cache busting for the emit cache.
Closes #105

feat: implement `Hash` on `EmitOptions`

---

.github/workflows/ci.yml
.github/workflows/publish.yml
.github/workflows/release.yml
scripts/deps.ts

This allows us to run a github action workflow to bump the version and do a release.

chore: add publish workflow for doing a release

---

.github/workflows/release.yml

I thought it would pull this in from the PAT somehow, but it doesn't which I guess makes sense.
```
Author identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident name (for <runner@fv-az275-961.go2hi5et44qedpdz5zrtt3gknc.xx.internal.cloudapp.net>) not allowed
error: Uncaught (in promise) Error: Exited with code: 128
throw new Error(`Exited with code: ${code}`);
```

chore: fix release script

---

src/cjs_parse.rs

We're going to cache this information in the CLI on a per module basis.

feat: make `CjsAnalysis` implement Serialize & Deserialize

---

src/lexing.rs
src/transpiling/mod.rs
src/types.rs

Missed doing this in the last PR (sorry). Noticed in the integration tests in dprint-plugin-typescript.

fix: indent diagnostic code two spaces

---

src/types.rs

My working tree is in a bad state so I missed this while doing searches for `Diagnostic`. It's necessary in deno_emit. I'll publish a patch for this fix.

fix: Diagnostic - Expose `from_swc_error`

---

src/media_type.rs

Closes #133
The mappings in `as_content_type()` are a suggestion based on `from_content_type()` and web searches.
`from_file_extension()` is case-sensitive to file extensions while `from_path()` is case-insensitive.  
If the crate user has non-lower-case extensions, they can transform them once to avoid every library function from having to do the transformation.
Changed return type of `as_ts_extension()` to `'static`. If this change is wrong, I'll also need to remove the `'static` from `as_content_type()`.

feat: add as_content_type() and make from_path() public

---

src/media_type.rs

TypeScript now considers all `.d.*.ts` files as declaration files so we need to do the same.

fix(media_type): handle .d.*.ts being a declaration file

---

src/transpiling/mod.rs

I've recently run into the issue that `TranspiledSource` is not `Clone`, requiring me to manually clone each field. Considering that a derive is trivial here, it should hopefully save some headaches in the future.
I've also implemented all other relevant traits from STD, based on https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits.

Implement common traits for `TranspiledSource`

---

src/transpiling/mod.rs

Enables support for JSX namespaces by setting `throw_if_namespace` to `false`.
Also added test for namespace on tag and attribute.
Closes #154

feat: enable jsx namespace support by default (#154)

---

Cargo.lock
Cargo.toml
src/transpiling/mod.rs

I broke const enums in swc for us when using ts_is_enum_mutable (then fixed them today)

fix: const enums weren't transpiled correctly

---

src/transpiling/jsx_precompile.rs
src/transpiling/jsx_string.rs
src/transpiling/mod.rs

This PR introduces a new JSX transform that is optimized for server-side rendering. It works by serializing the static parts of a JSX template into static string arrays at compile time. Common JSX templates render around 200-500 nodes in total and the transform in this PR changes the problem from an object allocation to string concatenation one. The latter is around 7-20x faster depending on the amount of static bits inside a template. For the dynamic parts, this transform falls back to the `automatic` runtime one internally.
Traditionally, JSX leaned quite heavily on the Garbage Collector because of its heritage as a templating engine for in-browser rendering.
```tsx
// input
const a = <div className="foo" tabIndex={-1}>hello<span /></div>
// classic Transform
const a = …
```

feat: precompile JSX to string transform

---

src/transpiling/jsx_precompile.rs

Follow up to https://github.com/denoland/deno_ast/pull/162
We should only ever normalize attributes (`className` -> `class`) of HTML elements and never for components.

fix: jsx component props being normalized

---

src/transpiling/jsx_precompile.rs

You learn something new every day! Turns out that contrary to standard JS string literals, JSX strings are allowed to span multiple lines.
```jsx
<Foo
description="Register a module with the third party
registry."
/>
```
When we convert that to a `jsx()` call and the values to standard string literals we need to account for this and normalize them back to a valid JS strings.
```jsx
jsx(Foo, { description="Register a module with the third party registry." });
```

fix: multiline JSX string conversion to string

---

src/transpiling/jsx_precompile.rs

Ran into a bug where we didn't quote non-identifier object properties like `aria-label`.
```tsx
// before
const a = { aria-label: "foo" }
// after
const a = { "aria-label": "foo" }
```

fix: non-identifier properties not quoted

---

src/transpiling/jsx_precompile.rs

Similar to text nodes in HTML, JSXText nodes that have surrounding whitespace can be trimmed in most scenarios. This makes the compilation output cleaner and allows us to flatten children arrays if only a single child remained after dropping unnecessary nodes.
Before: 
```jsx
_jsxssr($$_tpl_1, _jsx(Head, {
children: [
"\n\n        ",
_jsxssr($$_tpl_2),
"\n\n        ",
_jsxssr($$_tpl_3),
"\n\n        ",
_jsxssr($$_tpl_4),
"\n\n        ",
_jsxssr($$_tpl_5),
"\n\n\n\n        ",
"\n\n        ",
_jsxssr($$_tpl_6),
"\n\n\n\n        ",
_jsxssr($$_tpl_7),
"\n\n        ",
_jsxssr($$_tpl_8),
"\n\n      "
]
})
```
After
```jsx
_jsxssr($$_tpl_1, _jsx(Head, {
children: [
_jsxssr($$_tpl_2),
_jsxssr($$_tpl_3),
_jsxssr($$_tpl_4),
_jsxssr($$_tpl_5),
_jsxssr($$_tpl_6),
_jsxssr($$_tpl_7),
_jsxssr($$_tpl_8) …
```

fix: drop unnecessary whitespace

---

src/transpiling/jsx_precompile.rs

Missed one case of unnecessary whitespace in https://github.com/denoland/deno_ast/pull/169

fix: whitespace for single component child

---

src/transpiling/jsx_precompile.rs

This PR ensures that we insert template declarations after the last import.
Before:
```tsx
import { jsxssr as _jsxssr } from "react/jsx-runtime";
const $$_tpl_1 = [
"<div></div>"
];
import Foo from "./foo.ts";
import Bar from "./bar.ts";
const a = _jsxssr($$_tpl_1);
```
After:
```tsx
import { jsxssr as _jsxssr } from "react/jsx-runtime";
import Foo from "./foo.ts";
import Bar from "./bar.ts";
const $$_tpl_1 = [
"<div></div>"
];
const a = _jsxssr($$_tpl_1);
```

feat: insert jsx tpl after last import statement

---

src/transpiling/jsx_precompile.rs

When we encounter a numeric JSX attribute value `<img width={100} />`, we can serialize it ourselves rather than going through `jsxattr()`. This is a minor perf optimization.

feat: serialize numeric jsx attribute values

---

src/transpiling/jsx_precompile.rs
src/transpiling/mod.rs

This PR adds some logic to the new JSX transforms that allows it to merge serializable JSX children together. A node is deemed serializable when it is text, or is a serializable HTML node. This addresses the following scenarios where we'd generate more templates than necessary:
```jsx
// input
<div>foo{" "}bar</div>
// before
const tpl = [
"<div>foo",
"",
"bar</div>"
]
jsxssr(tpl, " ")
// after
const tpl = [
"<div>foo bar</div>",
]
jsxssr(tpl)
```
This scenario happens often enough in our code bases that this optimization should be worth it.

feat: merge serializable jsx children

---

src/transpiling/jsx_precompile.rs

Noticed a case where we were still adding JSX templates before an import statement. Our heuristic wasn't sufficient and didn't take empty statements or export declarations into account.

fix: jsx templates added before imports

---

src/transpiling/jsx_precompile.rs

HTML has a finite set of boolean attributes whose presence is interpreted as `true`, regardless of the actual attribute value and when it's not present it's interpreted as `false`. Knowing that, we can bypass calling into `jsxattr` to serialize and encode the value ourselves. If the value is a boolean literal we can serialize or skip the attribute ourselves too.
It probably doesn't matter much for perf in the grand scheme of things, but I guess why not go all in.
```jsx
// input
<input type="checkbox" checked required={foo} />
// before
const $$_tpl_1 = [
'<input type="checkbox" ',
">"
];
const a = _jsxssr($$_tpl_1, jsxattr("checked", true), jsxattr("required", foo));
// after
const $$_tpl_1 = [
'<input type="checkbox" checked ',
">"
];
const a = _jsxssr($$_tpl_1, foo ? "required" : ""); …
```

feat: optimize boolean attr handling

---

src/transpiling/jsx_precompile.rs
src/transpiling/mod.rs

Currently, this transform doesn't really have a `development` behavior really. Exposing this in the transform options is therefore confusing.
What we did when `development: true` is that we imported from `jsx-dev-runtime` and called `jsxDEV` instead of `jsx`, but that has been more or less regarded as a design flaw of the jsx runtime proposal. These days everyone just aliases `jsx-dev-runtime` and `jsx-runtime` to the exact same file and aliases `jsxDEV` to `jsx`. The only difference between those functions is that `jsxDEV` receives more parameters about call location. Everyone just treats that as optional arguments to `jsx` these days.
For all those reasons it's best if we drop the `development` option of the precompile transform.

fix: drop development for precompile JSX transform

---

src/transpiling/jsx_precompile.rs
src/transpiling/mod.rs

We settled on these ones:
- `jsxTemplate`
- `jsxAttr`
- `jsxEscape`
- `jsx`

chore: rename jsx precompile functions

---

src/transpiling/jsx_precompile.rs

When we receive a dynamic value that we cannot analyze statically we need to ensure that it is escaped properly before processing it. This PR adds a new `jsxEscape()` function from the jsx runtime to support that.
The reason the new transform is fast is because it only concerns itself with concatenating strings together. To make this work efficiently `jsxssr` expects values to be pre-escaped. This is necessary to make `jsxattr` performant, otherwise you'd need to allocate the full props object again.
```jsx
// input
<div>{foo}</div>
// out
jsxssr(tpl, jsxEscape(foo))
```

feat: jsx ensure dynamic values are escaped

---

src/transpiling/mod.rs

On `main` the code `{ 1; }` transpiles to
`{ 1; }//# sourceMappingURL=...`
This PR fixes this to transpile to `{ 1; }\n//# sourceMappingURL=...`

fix: ensure newline before inline sourcemap

---

Cargo.lock
Cargo.toml
src/dep_graph.rs
src/lib.rs

Moves swc_ecma_dep_graph back into denoland code. I'll open a separate PR with improvements to this.
See https://github.com/swc-project/swc/discussions/8289

feat: move back swc_ecma_dep_graph into deno_ast

---

.github/workflows/release.yml
Cargo.toml
deno.json
scripts/deps.ts
scripts/repos.ts
scripts/update_swc_deps.ts

Adds a script that automatically updates the Cargo.toml with the latest deps. I got tired of manually doing this.

chore: add script for automatically updating swc dependencies

---

.github/workflows/release.yml
rust-toolchain.toml
src/comments.rs
src/dep.rs
src/parsed_source.rs
src/parsing.rs
src/transpiling/mod.rs

Need this in order to do module analysis from an swc module without a `ParsedSource`

feat: expose analyzing deps without a ParsedSource and improvements to Comments

---

Cargo.lock
Cargo.toml

This fixes many issues with swc emitting TypeScript code in an AST (emphasis: TypeScript, not TS stripped to JS as it usually does).

fix: update swc_ecma_parser to 0.141.37

---

src/parsed_source.rs
src/parsing.rs

With fast remote type checking I need the ability to do scope analysis for only certain specifiers. This started getting really complicated and I think it's easier to just do this on demand. The catch is that there can only be one reference to the underlying data in the `ParsedSource` or else a whole clone happens, but this is generally how things work for us anyway.

feat: ability to add scope analysis to a `ParsedSource`

---

src/transpiling/mod.rs
src/transpiling/tc39_decorator_proposal_output.txt

Follow up to https://github.com/denoland/deno_ast/pull/201 that actually
supports [TC39 Decorator Proposal](https://github.com/tc39/proposal-decorators).
`EmitOptions::use_decorators_proposal` can be used to transpile
to match proposal semantics.

feat: Add support for decorator proposal

---

src/diagnostics.rs
src/types.rs

This works better with Cow for when a diagnostic contains a diagnostic that returns these methods from the inner diagnostic. With `impl Display` you need to convert everything into a known concrete type on the outer diagnostic (ex. call to_string() on everything).

refactor(diagnostics): use `Cow<str>` instead of `impl Display`

---

Cargo.lock
Cargo.toml
src/diagnostics.rs

Some tests in deno_doc failed on the CI because on Windows, unix paths used in the tests like `file:///mod.ts` would stay as a file specifier instead of being converted to a path. This makes it work the same way on all platforms.

fix(diagnostics): add windows fallback code to display unix paths

---

src/transpiling/jsx_precompile.rs

The JSX precompile transform was a bit overzealous when escaping component children that were text nodes. These must not be pre-escaped and instead must be passed as is to the component, otherwise they will be escaped multiple times.
Fixes https://github.com/denoland/deno/issues/22577

fix: precompile don't escape component text children

---

src/transpiling/mod.rs

Closes https://github.com/denoland/deno_ast/issues/216

fix(emit): make source_map work

---

src/transpiling/jsx_precompile.rs

This PR fixes an issue in the JSX precompile transform where leading and trailing whitespace would not be removed when composed of tab characters.
Fixes https://github.com/denoland/deno/issues/23030

fix: tab whitespace not removed in JSXText

---

Cargo.lock
Cargo.toml
src/emit.rs
src/transpiling/mod.rs

Closes https://github.com/denoland/deno_ast/issues/118

feat: return structured error from `deno_ast::ParsedSource::transpile`

---

.github/workflows/ci.yml
.github/workflows/release.yml
src/emit.rs
src/transpiling/mod.rs

Follow up to https://github.com/denoland/deno_ast/pull/237
The result is an enum to ensure the caller thinks about it when transpiling while owned is a performance issue (but we'd rather not crash for it).
We can land this sometime in the future.

feat(BREAKING): consolidate to a single `transpile` method

---

src/transpiling/jsx_precompile.rs
src/transpiling/mod.rs

In Fresh we do add some properties automatically to certain elements under the hood, like marking a link as "active" when it matches the current route among other things. For that we need to materialize the full `vnode` to know what kind of element were dealing with and what kind of other props it has.
To address this, this PR adds a new option to the transform which allows the user to pass an array of element names like `["a", "img"]` which should be excluded from being be precompiled by the transform. Plan is to add a new option in `deno.json#compilerOptions` for this.

feat: skip serialize option for jsx precompile

---

src/dep.rs

`import("./foo/" + value)` is now supported in addition to ``import(`./foo/${value}`)``.

feat: support string concat in dynamic import analysis

---

.gitignore
src/emit.rs
src/transpiling/jsx_precompile.rs
src/transpiling/mod.rs

We can avoid converting to utf-8 and instead just pass the module source as bytes to v8.

perf(emit): allow deferring or excluding utf8 conversion

---

src/transpiling/mod.rs

```
> hyperfine --warmup=3 ".\baseline.exe" ".\new.exe"
Benchmark 1: .\baseline.exe
Time (mean ± σ):     188.0 ms ±   6.6 ms    [User: 58.0 ms, System: 6.6 ms]
Range (min … max):   181.4 ms … 204.9 ms    14 runs
Benchmark 2: .\new.exe
Time (mean ± σ):     181.0 ms ±   4.8 ms    [User: 72.3 ms, System: 8.6 ms]
Range (min … max):   171.9 ms … 193.0 ms    16 runs
Summary
.\new.exe ran
1.04 ± 0.05 times faster than .\baseline.exe
```

perf: turn off jsx transforms for non-jsx compatible files

---

src/emit.rs
src/transpiling/mod.rs

People check for comments in `.toString()` so we need to keep the comments by default.

fix(BREAKING): flip `keep_comments` to `remove_comments`

---

src/cjs_parse.rs
src/comments.rs
src/dep.rs
src/parsed_source.rs
src/parsing.rs
src/scopes.rs
src/transpiling/mod.rs

This is taking 2% of execution in a benchmark I have. We don't need to create this when transpiling in Deno.

perf: lazily create `SourceTextInfo`

---

src/parsing.rs

For https://github.com/denoland/deno/issues/24122
We used to do this all the time when using SourceTextInfo, but now since we only work with the text this broke.

fix: strip BOM when parsing

---

src/transpiling/jsx_precompile.rs

This fixes an issue when an expression is passed as the component type like:
```tsx
<Foo.Bar fooBar={2} />
// Before this PR, incorrect casing
jsx(Foo.Bar, { foobar: 2 })
// After this PR
jsx(Foo.Bar, { fooBar: 2 })
```
Peviously, we wouldn't always treat this as a component and thus do props casing normalization. We must never touch the casing of component props though. Since we can't reliably determine if an expression holds a component or an element, we'll always treat it as a component.
Relevant Fresh issue https://github.com/denoland/fresh/issues/2539

fix: treat jsx expr tag names as components

---

src/transpiling/jsx_precompile.rs
src/transpiling/mod.rs

There are scenarios where framework plugins want to be able to intercept creation of properties. Some Fresh plugins like the current unocss and twind plugin want to intercept all `class/className` props to render CSS. All other properties not in the list should be treated as usual.
```tsx
const a = <div class="foo" />
// Before: Not interceptible
const tpl = [
'<div class="foo"></div>'
]
const a = jsxTemplate(tpl)
// After: interceptible if prop is excluded
const tpl = [
"<div ",
"></div>"
]
const a = jsxTemplate(tpl, jsxAttr("class", "foo"))
```
Related https://github.com/denoland/fresh/issues/2540

feat: option to force dynamic jsx precompile props

---

src/emit.rs
src/transpiling/mod.rs

Unreverts https://github.com/denoland/deno_ast/pull/92
Co-authored-by: Kitson Kelly <me@kitsonkelly.com>
Closes #94

feat: allow specifying a base for source maps

---

Cargo.lock
Cargo.toml
rust-toolchain.toml
src/dep.rs
src/source_map.rs
src/transpiling/jsx_precompile.rs
src/transpiling/mod.rs
src/transpiling/transforms.rs

~~I need to upgrade everything else before merging.~~

perf: upgrade to swc_ecma_parser 0.148

---

src/parsing.rs
src/types.rs

swc starting doing EOF errors on the last char instead of last non-whitespace char (which makes sense)

fix: do not show blank line diagnostic

---

src/source_map.rs

This was removed because it wasn't used, but actually it's used in JSR... so added back with a comment.

fix: add back `IntoSwcFileName`

---

src/parsing.rs

Fixes: https://github.com/denoland/deno_ast/issues/276
For some media types we know the source must be a certain syntax, so we can turn ParseMode::Program into ParseMode::Script or Module with that information.

refine parse mode by media type

---

src/transpiling/jsx_precompile.rs

When writing the precompile transform I missed to ensure that SVG attributes that are camelCased are kept that way. This PR addresses that.
Fixes https://github.com/denoland/deno/issues/25810

fix: preserve camelCased SVG attributes

---

rust-toolchain.toml
src/dep.rs
src/emit.rs
src/scopes.rs

This is towards improving our CJS support in deno graph (and thereby `deno compile`).

feat: analyze require calls as dynamic dependencies

---

src/cjs_parse.rs
src/dep.rs
src/emit.rs
src/parsed_source.rs
src/parsing.rs
src/transpiling/jsx_precompile.rs
src/transpiling/mod.rs

This is going to help with CJS support.

feat: use `Program` instead of `Module` more

---

Cargo.lock
Cargo.toml
src/emit.rs
src/parsing.rs
src/transpiling/jsx_precompile.rs
src/transpiling/mod.rs

Closes https://github.com/denoland/deno_ast/issues/282

perf: return a string when transpiling

---

src/parsed_source.rs
src/transpiling/mod.rs
src/types.rs

* Towards https://github.com/denoland/deno/issues/26651
* Related: https://github.com/swc-project/swc/issues/9694

fix: compute whether script

---

src/parsing.rs

Necessary to get `import Test = require("...");` properly working because those nodes are only available in a module.
Related: https://github.com/swc-project/swc/issues/9694

fix: parse cts files as module for now

---

Cargo.lock
Cargo.toml
src/text_changes.rs

Pretty trivial to maintain this now.
```rs
use deno_ast::apply_text_changes;
use deno_ast::TextChange;
fn main() {
let mut value = 0;
let mut large_string = String::new();
for _ in 0..10000 {
large_string.push_str("testing this out");
}
let changes = vec![TextChange::new(9, 10, "z".to_string()), TextChange::new(4, 6, "y".to_string()), TextChange::new(1, 2, "x".to_string())];
for _ in 0..10000 {
let final_str = apply_text_changes("testing this out", changes.clone());
value += final_str.len();
}
eprintln!("start: {}", value);
}
```
```
> hyperfine --warmup 4 "before.exe" "after.exe"
Benchmark 1: before.exe
Time (mean ± σ):       6.9 ms ±   0.6 ms    [User: 1.1 ms, System: 1.0 ms]
Range (min … max):     5.9 ms …   9.5 ms    259 runs
Benchmark 2: after.exe
Time (mean ± σ):       6.4 ms ± …
```

perf: pre-allocate text change string capacity

---

src/cjs_parse.rs
src/exports.rs
src/lib.rs

Method for analyzing the exports/re-exports for creating the CJS module wrapper when an ESM module is re-exported from the CJS one.

feat: add analyze_es_runtime_exports() method

---

Cargo.lock
src/parsing.rs

This PR updates deno_media_type to v0.2.8 and fixes the build.

chore: update deno_media_type

---

Cargo.lock
Cargo.toml
src/source_map.rs
src/transpiling/mod.rs
src/transpiling/transforms.rs

The swc Lock will fallback to RefCell when concurrent feature is not enabled, see https://github.com/swc-project/swc/blob/9676c9acc83cca4297f07abdc203f0ab8da36b2b/crates/swc_common/src/sync.rs#L37.
Closes https://github.com/denoland/deno_ast/issues/219
Closes #250

feat: add concurrent feature

---

Cargo.lock
Cargo.toml

- **upgrade deno_terminal to 0.2.2**
- **upgrade deno_error to 0.5.6**
- **upgrade once_cell to 1.21.1**
- **upgrade serde to 1.0.219**
- **upgrade string_capacity to 0.1.5**
- **upgrade base64 to 0.22.1**
- **upgrade sourcemap to 9.1.2**
- **upgrade pretty_assertions to 1.4.1**
- **upgrade serde_json to 1.0.140**
- **upgrade thiserror to 2.0.12**
- **update url dependency to 2.5.4**

chore: upgrade some dependencies

---

src/transpiling/jsx_precompile.rs

Noticed that we weren't escaping string literals when passed inside an expression as children.
```tsx
<div>{"\"a&>'"}</div>
```

fix(precompile): jsx child expression string literal not escaped

---

src/lib.rs

Right now we're busting the emit cache on CLI version, but we could bust it on deno_ast version instead probably.

feat: add version export
